name: build image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest

      - name: login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build and push to GHCR
        run: |
          docker buildx build --push \
            --tag ghcr.io/${{ github.repository_owner }}/metabase-autologin-proxy:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
